name: mirae
description: A new Flutter application.

version: 1.0.0+1

environment:
    sdk: ">=2.1.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^0.1.2
    location: ^3.0.0
    google_maps_flutter: ^1.2.0
    camera: ^0.7.0+2
    path: ^1.7.0
    path_provider: ^1.6.27
    folding_cell: "^1.0.0"
    expansion_card: "^0.1.0"
    flutter_svg:
    http:
    get:
    flutter_conditional_rendering:
    latlong:
    fluttertoast:
    url_launcher:

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
    assets:
        - assets/
        - assets/icon/
        - assets/icon/bottomNavigation/
        - assets/icon/map/

    fonts:
        - family: GoogleSans
          fonts:
              - asset: assets/fonts/GoogleSans-Regular.ttf
              - asset: assets/fonts/GoogleSans-Bold.ttf
                weight: 700
