name: mirae
description: A new Flutter application.

version: 1.0.0+1

environment:
    sdk: ">=2.1.0 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^0.1.2
    location: ^3.0.0
    google_maps_flutter: ^1.2.0
    flutter_svg:
    http:
    get:
    flutter_conditional_rendering:

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
    assets:
        - assets/
        - assets/icon/
        - assets/icon/bottomNavigation/
        - assets/icon/map/

    fonts:
        - family: GoogleSans
          fonts:
              - asset: assets/fonts/GoogleSans-Regular.ttf
