name: mirae
description: A new Flutter application.

version: 1.0.0+1

environment:
    sdk: ">=2.2.2 <3.0.0"

dependencies:
    flutter:
        sdk: flutter
    cupertino_icons: ^0.1.2
    location: ^3.0.0
    google_maps_flutter: ^1.2.0
    camera: ^0.7.0+2
    carousel_slider:
    path: ^1.7.0
    path_provider: ^1.6.27
    flutter_svg:
    http:
    get:
    flutter_conditional_rendering:
    latlong:
    fluttertoast:
    tflite:
    url_launcher:
    firebase_core:
    firebase_auth: ^0.15.0+1
    google_sign_in:
    web_scraper: ^0.0.6
    country_picker: ^2.0.0
    provider: ^5.0.0
    shared_preferences: ^0.5.3+4
    logger: ^0.7.0+2
    webview_flutter: ^0.3.19+9

dev_dependencies:
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true
    assets:
        - assets/
        - assets/icon/
        - assets/icon/bottomNavigation/
        - assets/icon/map/
        - assets/models/ssd_mobilenet.tflite
        - assets/models/labels.txt

    fonts:
        - family: GoogleSans
          fonts:
              - asset: assets/fonts/GoogleSans-Regular.ttf
              - asset: assets/fonts/GoogleSans-Bold.ttf
                weight: 700
